### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by xyjigsaw** [ojhaarjun1/Linux-Manpages-to-Knowledge-Graph#1]
Hi, there
Would you mind giving me a copy of Linux manpages data?

**Comment by kumar-mallikarjuna** [comment]
Hi,
I haven't processed all the manpages. The `graph.py` script uses `mman` to convert the manpages in the `manpath` to HTML. You'd need to specify which command you want though.

**Comment by xyjigsaw** [comment]
I got it. Thanks.
